### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by FR46M3N7-P4R71CL3** [galpt/kissvpn#1]
Hi,

This is a clever setup that uses Cloudflare upstream, but I'm failing to understand how this works end to end. To alleviate any privacy concerns, Can you kindly explain how the routing to "sg-r.0ms.dev" and the upstream work, without breaking the end-to-end encrypted wireguard tunnel, say to Cloudflare WARP?

Thanks for the great work!

**Comment by galpt** [comment]
@FR46M3N7-P4R71CL3 

Privacy-wise, VPN encryptions can't be cracked easily as already explained in the [Endpoint](https://github.com/galpt/kissvpn#endpoint) section.

To better understand it, we need to understand how computer networks work.
Most network traffic these days are using either TCP or UDP.

This includes any VPN protocols you could name of (OpenVPN, WireGuard, V2Ray, just the name of few).
OpenVPN & WireGuard VPNs transfer your data through TCP or UDP, but they add another encryption layer before sending your data via TCP/UDP.

You need to make a custom solution to handle the TCP/UDP traffic so you can route them to/from your own servers.
In this case we're implementing our own solution, and unfortunately this won't be disclosed to the public.

But what people should know about - if they ever have privacy concerns - is that we don't need to break the encrypted traffic to handle TCP/UDP.

Let's say someone made a QUIC-based VPN implementation where we're sending the VPN traffic using the [QUIC protocol](https://www.chromium.org/quic/).
You don't need to break the QUIC-encrypted traffic as it is using UDP underneath.
All you need to do is to make your own way to handle the traffic at the UDP-level.

**Comment by FR46M3N7-P4R71CL3** [comment]
Makes perfect sense, thanks.
