### ISSUE TITLE
NOT WORK - [Peer] ... Endpoint = net.0ms.dev:11111

### ISSUE THREAD

**Issue by chelaxian** [galpt/kissvpn#2]
Hi! 

```
[Peer]
...
Endpoint = net.0ms.dev:11111
```

This peer not work in cloudflare warp wireguard config.

While any host and port works from:
162.159.193.1-10
162.159.192.1-254
162.159.195.1-254

ports 500,4500,2408,1701

i suppose you use some kind of UDP-proxy to load balance traffic to this IP range and ports, because original host "engage.cloudflareclient.com" only resolve its name to nearest IP in CDN and make no LB and failover to other ports.

But your host and port now not working :(
Can you please fix it?
Thanks!

**Comment by galpt** [comment]
@chelaxian 

Sorry for the inconvenience.
We did a ton of customizations to the whole server to make sure everything's low latency.
Now the server will adjust Warp's speed to make sure the network stays responsive.

Tests from https://speed.cloudflare.com/ should give you a `Good` or even `Great` if you're lucky.
Note that the endpoint is located in SG, so the result will depend on that factor too.

The endpoint should work just fine now.

Feel free to open a new issue or send an email to `ask@0ms.dev` in case this happens again.
Closing this issue now.
